name: Our Big Test
pname: our_big_test
description: This is a first test for a package here
version: 0.2.8
icon: brain
private: false
base: true
category: folder_and_file_management
python:
  - '3.9'
  - '3.10'
  - '3.11'
requirements:
  - numpy
  - pandas
