name: "Mario's Package"
pname: mario_package
description: This is Mario Private Package
version: 3.3.33
icon: brain
private: true
python:
  - '3.9'
  - '3.10'
  - '3.11'
requirements:
  - numpy
  - pandas
